eslint と prettierをフロントエンドのフォーマット修正のために導入しました。
Ryota-Onuma/Task-Manager pull request #8
Opened 2020-07-27 05:22 UTC by Ryota-Onuma

## 処理概要
- ① eslintをまず導入しました
- ② eslintの修正だと美しくないという記事が散見されたので、prettierも導入しました。
- ③ 上記を用いて、数種類のvueファイルを自動修正しました

## 要件・仕様

## 動作確認
Command + Sで保存時に、コードが自動修正されます。

## 特記
- file changed のうち、eslintrc.js と prettierrc.jsが重要ファイルです。それ以外のファイルのほとんどは、フォーマット修正によるものです。
-
## 意見をもらいたい箇所 

## 参考
- https://qiita.com/pg_yamaton/items/4405419f9a7a02e2dcba

2020-07-28 07:36 UTC, ch0b3 approved these changes
LGTM

2020-07-28 07:41 UTC, ch0b3 requested changes
.eslintrc.jsのスペース数は合ってますか？

2020-07-28 07:41 UTC, takashi-5 commented
気になった箇所あったのでLGTM外しました

2020-07-28 07:50 UTC, ShintaroSakai approved these changes
LGTM

2020-07-28 08:01 UTC, Ryota-Onuma commented
@takashi-5 
ご指摘ありがとうございます！
確かに整っていなかったので、eslintrc.jsのフォーマットを手元のeslintを用いて整えました
https://github.com/Ryota-Onuma/Task-Manager/pull/8/commits/ced8aa374aac46c2eed4720898809d34fce6cb39

2020-07-30 09:51 UTC, ShinobuYamaguchi approved these changes
LGTM

2020-08-03 01:17 UTC, merged